созданы ContactListFragment.kt и ContactDetailsFragment.kt и взаимодействие между ними. ColorPrimary #7f47c0, ColorAccent #6ce082
ametr1ne/App65s pull request #2
Opened 2021-10-18 14:38 UTC by ametr1ne

![device-2021-10-18-182602](https://user-images.githubusercontent.com/72300681/137752091-8c92634e-11cc-4622-b565-c721cd5dc2dc.png
![device-2021-10-18-182233](https://user-images.githubusercontent.com/72300681/137752182-286db9d4-bb89-4034-8323-9cc93319c0b2.png)
)

2021-10-22 20:37 UTC, VadimB95 commented
Привет, завтра в течение дня проверю твой пр

2021-10-25 05:28 UTC, VadimB95 requested changes
жду исправлений

2021-10-25 05:28 UTC, VadimB95 commented on app/build.gradle
> +    compileSdk 31
так всё, я наконец добрался

2021-10-25 05:28 UTC, VadimB95 commented on app/build.gradle
> +    compileSdk 31
зачем изменил compile sdk?

2021-10-25 05:28 UTC, VadimB95 commented on app/src/main/java/com/gmail/filanovsky/app65s/ContactDetailsFragment.kt
> +        activity?.title = "Детали контакта"
используй requireActivity()

2021-10-25 05:28 UTC, VadimB95 commented on app/src/main/java/com/gmail/filanovsky/app65s/ContactDetailsFragment.kt
> +        activity?.title = "Детали контакта"
и давай перенесем это в onViewCreated()

2021-10-25 05:28 UTC, VadimB95 commented on app/src/main/java/com/gmail/filanovsky/app65s/ContactListFragment.kt
> +        activity?.title = "Список контактов"
аналогично

2021-10-25 05:28 UTC, VadimB95 commented on app/src/main/java/com/gmail/filanovsky/app65s/ContactListFragment.kt
> +        view.setOnClickListener {
тоже в onViewCreated()

2021-10-25 05:28 UTC, VadimB95 commented on app/src/main/java/com/gmail/filanovsky/app65s/ContactListFragment.kt
> +
пустая строка

2021-10-25 05:28 UTC, VadimB95 commented on app/src/main/res/layout/activity_main.xml
> +<androidx.appcompat.widget.LinearLayoutCompat xmlns:android="http://schemas.android.com/apk/res/android"
отформатируй файл ctrl+alt+l

2021-10-25 05:28 UTC, VadimB95 commented on app/src/main/res/layout/activity_main.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
здесь не требуется ConstraintLayout, оставь самый простой FrameLayout

2021-10-25 05:28 UTC, VadimB95 commented on app/src/main/res/layout/contact_details.xml
> +        android:id="@+id/contact_avatar"
давай все id в camelCase, потом будет удобно с viewBinding

2021-10-25 05:28 UTC, VadimB95 commented on app/src/main/res/layout/contact_list_item.xml
> +            android:layout_width="207dp"
старайся верстать без таких магических значений. в большинстве случаев можно обойтись только маржинами. это я про весь макет

2021-10-25 05:30 UTC, VadimB95 commented
еще комментарий к пр обрезанный. сделай его нормальным

2021-10-25 17:55 UTC, ametr1ne commented on app/build.gradle
> +    compileSdk 31
![image](https://user-images.githubusercontent.com/72300681/138745710-b1ef7b78-4277-450f-8c14-f1deb0b372c1.png)
из за вот этой ошибки. После смены compile sdk на 31 версию, она исчезает и все компилится адекватно

2021-10-25 18:14 UTC, ametr1ne commented on app/src/main/java/com/gmail/filanovsky/app65s/ContactDetailsFragment.kt
> +        activity?.title = "Детали контакта"
исправил

2021-10-25 18:14 UTC, ametr1ne commented on app/src/main/res/layout/activity_main.xml
> +<androidx.appcompat.widget.LinearLayoutCompat xmlns:android="http://schemas.android.com/apk/res/android"
исправил

2021-10-25 18:14 UTC, ametr1ne commented on app/src/main/res/layout/activity_main.xml
> +    <androidx.constraintlayout.widget.ConstraintLayout
исправил

2021-10-25 18:14 UTC, ametr1ne commented on app/src/main/res/layout/contact_details.xml
> +        android:id="@+id/contact_avatar"
исправил

2021-10-25 18:14 UTC, ametr1ne commented on app/src/main/res/layout/contact_list_item.xml
> +            android:layout_width="207dp"
исправил

2021-10-25 18:38 UTC, VadimB95 commented on app/build.gradle
> +    compileSdk 31
Судя по всему, это произошло из-за того, что ты подключил зависимость "androidx.recyclerview:recyclerview:1.3.0-alpha01", которая тащит за собой последний androidx.core. В продакшн коде мы стараемся не использовать без необходимости альфа и бета версии либ. Но в учебном проекте допускается.

2021-10-25 18:40 UTC, VadimB95 commented on app/src/main/java/com/gmail/filanovsky/app65s/ContactDetailsFragment.kt
> +        requireActivity().title = "Детали контакта"
строку в ресурсы

2021-10-25 18:45 UTC, VadimB95 submitted a review, later dismissed

2021-10-25 18:57 UTC, VadimB95 requested changes
еще было бы плюсом, если бы ты завел readme, куда добавлял бы, что было сделано в каждом дз

2021-10-25 18:57 UTC, VadimB95 commented on .idea/misc.xml
>      <option name="filePathToZoomLevelMap">
папку .idea лучше бы вообще убрать из гита

2021-10-25 18:57 UTC, VadimB95 commented on app/src/main/res/layout/activity_main.xml
> +<androidx.appcompat.widget.LinearLayoutCompat
используй обычный (не compat)

2021-10-25 18:57 UTC, VadimB95 commented on app/src/main/res/layout/activity_main.xml
> +        android:id="@+id/fragment_container"
camel case

2021-10-25 18:57 UTC, VadimB95 commented on app/src/main/res/layout/contact_details.xml
> +        android:text="TextView"
в этом дз приму, но начиная со следующего все строки, которые будут видимы в ui, надо будет положить в ресурсы

2021-10-25 19:45 UTC, ametr1ne commented on app/src/main/java/com/gmail/filanovsky/app65s/ContactDetailsFragment.kt
> +        requireActivity().title = "Детали контакта"
исправил

2021-10-25 19:47 UTC, ametr1ne commented on .idea/misc.xml
>      <option name="filePathToZoomLevelMap">
исправил, добавил в gitignore

2021-10-25 19:55 UTC, VadimB95 commented on .idea/misc.xml
>      <option name="filePathToZoomLevelMap">
погугли еще, как выпилить из гита то, что там уже лежит (т.е. удали вообще папку .idea из репозитория)

2021-10-25 20:01 UTC, ametr1ne commented on .idea/misc.xml
>      <option name="filePathToZoomLevelMap">
исправил

2021-10-25 20:07 UTC, VadimB95 approved these changes

2021-10-25 20:08 UTC, merged